version: 2

project_name: grons

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# .deb (Ubuntu/Debian) and .rpm (Fedora/RHEL/CentOS)
nfpms:
  - id: packages
    package_name: grons
    vendor: gavasc
    homepage: https://github.com/gavasc/grons
    maintainer: gavasc
    description: Terminal UI for managing cron jobs.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}"

checksum:
  name_template: "checksums.txt"

aur_sources:
  - name: grons
    homepage: https://github.com/gavasc/grons
    description: Terminal UI for managing cron jobs.
    maintainers:
      - gavasc
    license: MIT
    private_key: "{{ .Env.AUR_SSH_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/grons.git"
    build: |-
      cd "${srcdir}/${pkgname}_${pkgver}"
      go build -ldflags="-s -w" -o grons .
    package: |-
      install -Dm755 "./grons" "${pkgdir}/usr/bin/grons"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
